import json
from langchain_ollama import ChatOllama
from langchain.schema import SystemMessage, HumanMessage

class Analytics:
    def __init__(self):
        self.local_llm = 'llama3.2'
        self.llm_json_mode = ChatOllama(model=self.local_llm, temperature=0, format='json')
        
        
    def generate_scores_and_cot(self,question:str,answer:str,context:str):
        hallucination_grader_instructions = """
        You are a grader evaluating the quality of a response generated by an assistant based on Keras documentation.

        You will be provided with the following:
        - **CONTEXT**: Information from the Keras documentation.
        - **ASSISTANT'S RESPONSE**: The assistant's response to be evaluated.

        ### Grading Criteria:

        1. **Grounding**: Ensure the ASSISTANT'S RESPONSE is fully grounded in the CONTEXT provided.
        2. **Accuracy**: Ensure the ASSISTANT'S RESPONSE does not introduce any information outside the scope of the CONTEXT or hallucinated details.

        ### Scoring:

        - **Score range**: Provide a score between **0 and 1**. A score of **1** means the response is fully grounded in the CONTEXT and does not include hallucinated information. A score of **0** means the response is not grounded in the CONTEXT or introduces hallucinated information.
        - Scores between **0 and 1** indicate the degree to which the response is grounded, with **higher scores** meaning better alignment with the CONTEXT.

        ### Feedback:

        - **Chain of Thought**: Provide a detailed, step-by-step explanation of why you assigned the given score. Clearly justify your conclusion based on the provided CONTEXT, avoiding assumptions or unsupported reasoning.

        ### Format:
        """

        # Grader prompt
        hallucination_grader_prompt = """FACTS: 

            {documents} 

            STUDENT ANSWER: 

            {generation}.

            ### Task:

            Return a JSON object with the following keys:
            - **score**: A floating-point number between 0 and 1. The closer the score is to 1, the better the response is grounded in the FACTS.
            - **chain_of_thought**: A detailed explanation of why you assigned the given score, explaining step-by-step how the response aligns or diverges from the FACTS.

            ### JSON Schema:
            {{
            "score": float,
            "chain_of_thought": "string"
            }}

        """
        
        hallucination_grader_prompt_formatted = hallucination_grader_prompt.format(documents=context, generation=answer)
        print("hallucination_grader_prompt_formatted",hallucination_grader_prompt_formatted)
        
        result = self.llm_json_mode.invoke([SystemMessage(content=hallucination_grader_instructions)] + [HumanMessage(content=hallucination_grader_prompt_formatted)])
        result = json.loads(result.content)
        

        
        answer_grader_instructions = """You are a grader evaluating the quality of a response generated by an assistant based on a user's query related to Keras documentation.
        
        You will be provided with the following:
        - **USER QUESTION**: The question asked by the user.
        - **ASSISTANT'S RESPONSE**: The assistant's response to the user query.

        ### Grading Criteria:

        1. **Accuracy**: The ASSISTANT'S RESPONSE should accurately address the USER QUESTION and provide relevant, useful information based on the query.
        2. **Completeness**: The ASSISTANT'S RESPONSE should fully answer the question, providing a clear and complete response.

        ### Scoring:

        - **Score range**: Provide a score between **0 and 1**. A score of **1** means the response fully addresses the USER QUESTION and provides relevant and complete information. A score of **0** means the response does not adequately address the USER QUESTION or is incomplete.
        - Scores between **0 and 1** indicate the degree to which the response meets the criteria, with **higher scores** meaning the response is more accurate and complete.

        ### Feedback:

        - **Chain of Thought**: Provide a detailed, step-by-step explanation for your score, justifying your conclusion based on the USER QUESTION and the ASSISTANT'S RESPONSE.
        """

        # Grader prompt
        answer_grader_prompt = """QUESTION: 

        {question}

        STUDENT ANSWER: 

        {generation}

        ### Task:

        Return a JSON object with the following keys:
        - **score**: A floating-point number between 0 and 1. The closer the score is to 1, the better the response addresses the USER QUESTION.
        - **chain_of_thought**: A detailed explanation of why you assigned the given score, explaining step-by-step how the response aligns or diverges from the USER QUESTION.

        ### JSON Schema:
        {{
        "score": float,
        "chain_of_thought": "string"
        }}"""
        
        answer_grader_prompt_formatted = answer_grader_prompt.format(question=question, generation=answer)
        print("answer grader prompt formatted \n",answer_grader_prompt_formatted)
        answer_grader = self.llm_json_mode.invoke([SystemMessage(content=answer_grader_instructions)] + [HumanMessage(content=answer_grader_prompt_formatted)])
        answer_grader = json.loads(answer_grader.content)
        
        def normalize_score(score):
            try:
                score = float(score)
                return max(0.0, min(1.0, score))  # Clamp between 0 and 1
            except (ValueError, TypeError):
                return 0.0  # Default to 0 if conversion fails
        
        return {
            "answerRelevance": {
                "score": normalize_score(answer_grader.get('score')),
                "reasoning": str(answer_grader.get('chain_of_thought', ''))
            },
            "groundedness": {
                "score": normalize_score(result.get('score')),
                "reasoning": str(result.get('chain_of_thought', ''))
            }
        }